# This is a basic workflow to help you get started with Actions

name: el otro

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  segundo-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Hola Hola Carola!"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Esta es la primera linea de codigo"
          echo "esta es la francesa"
          echo "esta es la tercera"
